---
- hosts: all
  become: true
  tasks:
    - name: Touch /etc/transmission-rss.conf
      file:
        path: /etc/transmission-rss.conf
        state: touch
        owner: root
        group: root
        mode: '0644'
    - name: Write /etc/transmission-rss.conf
      blockinfile:
        path: /etc/transmission-rss.conf
        block: |
          feeds:
            - url: {{rss_feed}}

          server:
            host: 'hp-9470m'
            port: 9091
            tls: false
            rpc_path: /transmission/rpc