---
- hosts: hp-9470m
  become: 'yes'
  # unfortunately this requires that you get the UUIDs of the disks before you can run this
  # one day perhaps I'll find a way to mount every drive based on their attributes
  # the last answer here has nothing to do with Ansible but does describe how to do it...
  # https://stackoverflow.com/questions/41292850/how-to-mount-all-partitions-listed-on-the-fstab-with-ansible
  tasks:
  - name: Create /mnt/drive1
    file:
      path: /mnt/drive1
      state: directory
  - name: Mount drive1
    mount:
      path: /mnt/drive1
      src: UUID=d165129d-52f2-4143-a78c-67e747cd4f54
      fstype: ext4
      opts: defaults
      state: present  
  - name: Create /mnt/drive3
    file:
      path: /mnt/drive3
      state: directory
  - name: Mount drive3
    mount:
      path: /mnt/drive3
      src: UUID=4d3650f1-1f6b-40b6-aff3-9d07ac032549
      fstype: ext4
      opts: defaults
      state: present
  - name: Create /mnt/drive4
    file:
      path: /mnt/drive4
      state: directory
  - name: Mount drive4
    mount:
      path: /mnt/drive4
      src: UUID=6319f6fc-1c79-4274-b06d-cb870a7a48b7
      fstype: ext4
      opts: defaults
      state: present
  - name: Run 'mount -a'
    command: mount -a