---
- hosts: all
  tasks:
  - name: make directory
    file:
      path: "/home/damon/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/damon/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/damon/.ssh/authorized_keys"
      line: "{{ pubkey }}"